### ISSUE TITLE
Contact Submit question

### ISSUE THREAD

**Issue by CupOfGeo** [Adrinlol/landy-react-template#41]
Hello first thank you for this template. I'm getting this error on contact submit
```
ERROR
Request failed with status code 404
    at createError (http://0.0.0.0:3000/static/js/vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js-n-46ba66.chunk.js:3361:15)
    at settle (http://0.0.0.0:3000/static/js/vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js-n-46ba66.chunk.js:3579:12)
    at XMLHttpRequest.onloadend (http://0.0.0.0:3000/static/js/vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js-n-46ba66.chunk.js:2814:7)   
```

i see this line where it says to set your url 
https://github.com/Adrinlol/landy-react-template/blob/6586a3ab499ebacd5e293a3c4c70d3fd1bf54123/src/common/utils/useForm.tsx#L25
so does that mean that I need to setup another web server to wait for these messages? I'm just logging the event instead now. Wondering what you and others are doing for it. Maybe send myself a text message or notify a discord channel? but I wouldn't wanna just make that info public.

**Comment by Adrinlol** [comment]
Hey @CupOfGeo, you are welcome!

The readymade contact form needs your REST API endpoint to post the form data to your server, that `url` variable is there for it.

**Comment by CupOfGeo** [comment]
Is that a separate REST API from this app I bc i wouldn't really wanna support that service as well. Im thinking I can add a post endpoint to this app that receives the request and then i can log it server side. console.log only logs it client side pretty new to react apps 🤦

**Comment by Adrinlol** [comment]
Correct, that is a separate REST API, this template only covers the client side code.
