### ISSUE TITLE
errors when submitting the form

### ISSUE THREAD

**Issue by PavanKumarGurram** [Adrinlol/landy-react-template#50]
I have added an api endpoint in useForm.tsx, but when I submit the form I received the errors:
Uncaught runtime errors:
×
ERROR
Network Error
    at createError (http://localhost:3000/static/js/vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js-n-46ba66.chunk.js:3356:15)
    at XMLHttpRequest.handleError (http://localhost:3000/static/js/vendors-node_modules_antd_es_config-provider_index_js-node_modules_antd_es_message_index_js-n-46ba66.chunk.js:2852:14)

**Comment by Adrinlol** [comment]
It can be a bit tricky to pinpoint the issue with just general error message. My suspicion is that it might involve either a port number discrepancy or a CORS issue. However, neither of these seem directly tied to the scope of our current project.
